security/models.py
import mongoengine as db
from flask.ext.security import UserMixin, RoleMixin
from flask.ext.mongoengine.wtf import model_form
__author__ = 'Donal_Carpenter'

class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=255, unique=True)
    description = db.StringField(max_length=255)

    def __repr__(self):
        return '<role {} {}>'.format(id, self.name)

class User(db.Document, UserMixin):
    email = db.StringField(max_length=255, unique=True)
    password = db.StringField(max_length=255)
    active = db.BooleanField(default=True)
    confirmed_at = db.DateTimeField()
    roles = db.ListField(db.ReferenceField(Role), default=[])
    social_provider = db.StringField()
    social_id = db.StringField()

    def __repr__(self):
        return '<user {} {}>'.format(id, self.email)

UserForm = model_form(User)

security/__init__.py
__author__ = 'Donal_Carpenter'
from app import app, db
from flask.ext.security import Security, MongoEngineUserDatastore
from security.models import User, Role

app.config['SECURITY_POST_LOGIN'] = '/profile'

user_datastore = MongoEngineUserDatastore(db, User, Role)
security = Security(app, user_datastore)


@app.before_first_request
def create_dummy_user():
    pass
    #user_datastore.create_user(email='donal.carpenter@yahoo.com', password='password')

security/controller.py
__author__ = 'Donal_Carpenter'

from flask import Blueprint, jsonify, request, render_template, flash, Response, redirect, url_for
from security.models import UserForm
from security.oauth import OAuthSignIn
from flask.ext.security import login_required, current_user, login_user
from security.models import User
from mongoengine import Q

profile_blueprint =  Blueprint('profile', __name__, url_prefix='/authorize')

@profile_blueprint.route('/')
@login_required
def profile():
    uf = UserForm()
    uf.email = current_user.email
    return render_template('security/user_profile.html', user_profile_form=uf)


@profile_blueprint.route('/init/<provider>')
def authorize(provider):
    if not current_user.is_anonymous():
        return url_for('home')
    provider = OAuthSignIn.get_provider(provider)
    if(provider == None):
        return Response("Provider not recognized", 404)
    return provider.authorize()

@profile_blueprint.route('/callback/<provider_name>')
def callback(provider_name):
    if not current_user.is_anonymous():
        return url_for("lolcat.home")
    provider = OAuthSignIn.get_provider(provider_name)
    if(provider == None):
        return Response("Provider not recognized", 404)
    social_id, email = provider.callback()
    #social_id, email= ("facebook$12234", 'donal.carpenter@yahoo.com')
    user = User.objects(Q(social_provider=provider_name) & Q(social_id=social_id)).first()
    if user == None:
        user = User(email=email, social_provider=provider_name, social_id=social_id)
        user.save()
        flash("Your account has been created. enjoy the lols and the cats")
    login_user(user)
    return redirect(url_for("lolcat.home"))

templates/security/login_user.html
{% from "_macros.html" import render_form, render_field_with_errors, render_checkbox_field, render_field %}

{%  extends "base.html" %}

{%  block page_header %}
<h1>Login to do whatever it was you were doin</h1>
{%  endblock %}

{%  block content %}

    <a href="{{  url_for('profile.authorize', provider='facebook') }}">Login with Facebook</a>

{{ render_form(login_user_form, action_url=url_for_security('login')) }}

{%  endblock %}

templates/security/register_user.html
{% from "_macros.html" import render_form, render_field_with_errors, render_checkbox_field, render_field %}

{%  extends "base.html" %}

{%  block page_header %}
<h1>Register</h1>
{%  endblock %}

{%  block content %}

{{ render_form(register_user_form, action_url=url_for_security('register')) }}

{%  endblock %}

templates/security/user_profile.html
{% from "_macros.html" import render_form, render_field_with_errors, render_checkbox_field, render_field %}

{%  extends "base.html" %}

{%  block page_header %}
<h1>Register</h1>
{%  endblock %}

{%  block content %}

{{ render_form(user_profile_form, action_url=url_for_security('register')) }}

{%  endblock %}