views.py
from flask import Blueprint, jsonify, request, render_template, flash, Response, redirect, url_for
from models.LolCat import LolCat, Comment, CommentReply
from math import ceil
from flask.ext.security import login_required
import forms

lol_cat_blueprint = Blueprint('lolcat', __name__)
items_per_page = 4


@lol_cat_blueprint.route('/')
@lol_cat_blueprint.route('/lolcats/<int:page>')
def home(page=0):
    """
    Gets the home page. This has a list of lolats

    :param page: the page to return
    :return: The rendered view for the landing page
    """
    res = []
    start_index = page * items_per_page
    results = LolCat.objects.order_by("-created_at")[start_index:start_index + items_per_page]
    total = results.count(with_limit_and_skip=False)
    for lc in results:
        res.append(lc)
    return render_template("list.html", cats=res, total=total, page=page, pages=ceil(total / items_per_page))


@lol_cat_blueprint.route('/lolcat/<catid>')
def one(catid):
    """
    This is the detail view for a single lolcat
    :param catid:
    :return:
    """
    if (not catid):
        # this needs to return a 400 Bad Request
        pass

    puss = LolCat.objects.get_or_404(id=catid)
    commentForm = forms.CommentForm()
    replyForm = forms.CommentReplyForm()
    return render_template("detail.html", cat=puss, form=commentForm, replyForms=(replyForm, ))


@lol_cat_blueprint.route('/lolcat/<catid>/comments', methods=['POST'])
def save_comment(catid):
    """
    This adds a comment to a lolcat

    :param catid: the lolcat to add the comment to
    :return:should redirect back to the lolcat detail view
    """
    puss = LolCat.objects.get_or_404(id=catid)
    form = forms.CommentForm()
    if (not form.validate_on_submit()):
        flash("There were some problems validating that comment, you can try again...", "warning")
        replyForm = forms.CommentReplyForm()
        return render_template("detail.html", cat=puss, form=form, replyForms=(replyForm, ))

    comment = Comment(author=form.author.data, comment=form.comment.data, lolcat=puss.id)
    comment.save()
    puss.update(push__comments=comment)
    puss.save()
    flash("your lovely new comment has been added to {}".format(puss.title), "success")
    return redirect(url_for('.one', catid=catid), code=302)


@lol_cat_blueprint.route("/lolcat/<catid>/comment/<commentid>/replies", methods=['POST'])
def save_comment_reply(catid, commentid):
    """
    This will save a single comment reply
    :param catid: the id of the lolcat
    :param commentid: the comment to add the reply to
    :return: redirects back to the single lolcat page
    """
    form = forms.CommentReplyForm()
    if (not form.validate_on_submit()):
        flash("there was an error adding your comment reply - try again", "warning")
        cat = LolCat.objects.get_or_404(id=catid)
        form.comment_id = commentid
        emptyForm = forms.CommentReplyForm()
        emptyForm.author.data = ""
        emptyForm.comment.data = ""
        return render_template("detail.html", cat=cat, form=forms.CommentForm(), replyForms=(emptyForm, form))

    comment = Comment.objects.get_or_404(id=commentid)
    reply = CommentReply(author=form.author.data, comment=form.comment.data)
    comment.replies.append(reply)
    comment.save()
    flash("your new comment reply has been saved", "success")
    return redirect(url_for('.one', catid=catid), code=302)


@lol_cat_blueprint.route("/lolcat/new")
@lol_cat_blueprint.route('/lolcat/edit/<catid>')
@login_required
def edit(catid=None):
    """
    This is view displays the form to add a new lolcat or edit an existing lolcat
    :param catid:the id of the cat to edit, or None if this is a new lolcat
    :return: the view that has the lolcat form
    """
    if catid:
        puss = LolCat.objects.get_or_404(id=catid)
    else:
        puss = None
    form = forms.LolCatUploadForm(obj=puss)
    return render_template("create.html", form=form)


@lol_cat_blueprint.route('/lolcat/save', methods=['POST'])
def save_lolcat():
    """
    This is where lolcats get saved to our db

    :return:goes to the detail view of the lolcat
    """
    try:
        form = forms.LolCatUploadForm()
        if (not form.validate_on_submit()):
            flash("There were some problems validating that lolcat, you can try again...", "warning")
            return render_template("create.html", form=form)

        cat_id = form.id.data
        if (cat_id):
            # this is an edit so retrieve cat details from mongo
            flash_message = "Cat {} has been updated"
            cat = LolCat.objects.get_or_404(id=cat_id)
        else:
            # this is a new lolcat
            flash_message = "Cat {} has been created"
            cat = LolCat()

        cat.title = form.title.data
        cat.blurb = form.blurb.data
        cat.source = form.source.data

        if (form.image_data.has_file()):
            if (cat.image_data):
                cat.image_data.delete()  # we need to this first. otherwise the new one will not save

            file = form.image_data.data
            cat.image_data.new_file()
            cat.image_data.content_type = file.content_type
            cat.image_data.write(file.stream)
            cat.image_data.close()

        cat.save()
        flash(flash_message.format(cat.title), "success")
        return render_template("detail.html", cat=cat, form=forms.CommentForm(), replyForms=(forms.CommentReplyForm(),))
    except Exception as e:
        return render_template("error.html", err=e)


@lol_cat_blueprint.route('/lolcat/delete/<catid>')
@login_required
def delete(catid):
    """
    This will permanentley delete a lolcat
    :param catid: the id of the lolcat to delete
    :return: redirects to home
    """
    cat = LolCat.objects.get_or_404(id=catid)
    cat.delete()
    flash("Cat {} has been deleted".format(cat.title), "success")
    return home()


@lol_cat_blueprint.route('/lolcat/image/<catid>')
def image_data(catid):
    """
    This gets the bytes that constitute the lolcat image
    :param catid: the cat id that you want to see
    :return:a byte[] stream
    """
    cat = LolCat.objects.get_or_404(id=catid)
    data = cat.image_data.read()
    ct = cat.image_data.content_type

    return Response(response=data, content_type=ct)

templates/_macros.html
{% macro render_field(field) %}
  <div class="form-group">{{ field(**kwargs)|safe }}</div>
{% endmacro %}

{# Renders field for bootstrap 3 standards.

    Params:
        field - WTForm field
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
#}
{% macro render_field_with_errors(field, label_visible=true) -%}

    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if (field.type != 'HiddenField' and field.type !='CSRFTokenField') and label_visible %}
            <label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}

{% macro render_field(field) %}
  <div class="form-group">{{ field(class_='form-control', **kwargs)|safe }}</div>
{% endmacro %}

{# Renders checkbox fields since they are represented differently in bootstrap
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_checkbox_field(form.remember_me) }}
 #}
{% macro render_checkbox_field(field) -%}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
{%- endmacro %}

{# Renders radio field
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_radio_field(form.answers) }}
 #}
{% macro render_radio_field(field) -%}
    {% for value, label, _ in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{# Renders WTForm in bootstrap way. There are two ways to call function:
     - as macros: it will render all field forms using cycle to iterate over them
     - as call: it will insert form fields as you specify:
     e.g. {% call macros.render_form(form, action_url=url_for('login_view'), action_text='Login',
                                        class_='login-form') %}
                {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
                {{ macros.render_field(form.password, placeholder='Input password', type='password') }}
                {{ macros.render_checkbox_field(form.remember_me, type='checkbox') }}
            {% endcall %}

     Params:
        form - WTForm class
        action_url - url where to submit this form
        action_text - text of submit button
        class_ - sets a class for form
    #}
{% macro render_form(form, action_url='', action_text='Submit', class_='', btn_class='btn btn-default') -%}

    <form method="POST" action="{{ action_url }}" role="form" class="{{ class_ }}">
        {{ form.hidden_tag() if form.hidden_tag }}
        {% if caller %}
            {{ caller() }}
        {% else %}
            {% for f in form %}
                {% if f.type == 'BooleanField' %}
                    {{ render_checkbox_field(f) }}
                {% elif f.type == 'RadioField' %}
                    {{ render_radio_field(f) }}
                {%  elif f.type == 'SubmitField' %}
                    <input type="submit" class="{{ btn_class }}" value="{{ f.label.text }}" />
                {% else %}
                    {{ render_field_with_errors(f) }}
                {% endif %}
            {% endfor %}
        {% endif %}
    </form>
{%- endmacro %}

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Python Flask MongoDb Bootstrap Angular</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>
<style>
    body { margin-top: 70px;}
</style>
<body>

  {%- block topbar -%}

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
              <a class="navbar-brand" href="{{ url_for('lolcat.home', page=0) }}">The Lolcat Fancier</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="{{ url_for('lolcat.home', page=0) }}">home</a></li>
            <li><a href="{{ url_for('lolcat.edit') }}">new</a></li>
{% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('security.logout') }}">logout</a></li>
{%  else %}
            <li><a href="{{ url_for('security.login') }}">login</a></li>
            <li><a href="{{ url_for('security.register') }}">register</a></li>
{%  endif %}

        </ul>
      </div>
    </nav>

    {%- endblock -%}

    <div class="container">
      <div class="content">
        {% block page_header %}{% endblock %}

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                <div class=flashes>
                {% for category, message in messages %}
                <div class="alert alert-{{  category or "success" }}">{{ message }}</div>
                {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
      </div>
    </div>

    {% block js_footer %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</body>
</html>

templates/create.html
{%  extends "base.html" %}

{%  block page_header %}
<h2>{{ heading }}</h2>
{%  endblock %}

{%  block content %}

<form role="form" method="post" action="{{ url_for('.save_lolcat') }}" enctype="multipart/form-data">
    {{  form.hidden_tag() }}
    <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.blurb.label }}
        {{ form.blurb(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.source.label }}
        {{ form.source(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.image_data.label }}
        {{ form.image_data(class_="form-control") }}
    </div>

    <button type="submit" class="btn btn-default">Save</button>
</form>

{% endblock %}

templates/detail.html
{%  extends "base.html" %}

{%  block page_header %}
    <h2>{{ cat.title }}</h2>
{% endblock %}

{%  block content %}


    <div class="jumbotron">
        <h3 class="media-heading">{{ cat.title }}</h3>
        <img class="media-object" src="{{ url_for('.image_data', catid=cat.id) }}" />
        <p>
        {{ cat.blurb }}

    </p><a href="{{ url_for('.edit', catid = cat.id) }}" aria-label="Left Align"><span class="glyphicon glyphicon-edit" aria-label="true"></span> edit</a>
        <a href="{{ url_for('.delete', catid = cat.id) }}"><span class="glyphicon glyphicon-erase" aria-label="true"></span> delete</a></div>

    {% for comment in cat.comments %}
    <div class="panel panel-default">
        <div class="panel-heading">{{ comment.author }}</div>
        <div class="panel-body">{{  comment.comment }}</div>

            <ul class="list-group">

            {%  for reply in comment.replies%}

                <li class="list-group-item">
                    <h4 class="list-group-item-heading">{{ reply.author }}</h4>
                    <p class="list-group-item-text">{{ reply.comment }}</p>
                </li>

            {% endfor %}

                <li class="list-group-item">
                    <div class="container">
                {%set rf = replyForms | selectattr("comment_id", "equalto", comment.id | string) | first | default(replyForms[0])  %}
                    <form role="form" method="post" action="{{ url_for('.save_comment_reply', catid=cat.id, commentid=comment.id) }}" class="form-inline">
                        {{  rf.hidden_tag() }}
                        <div class="form-group">
                            {{ rf.author.label }}
                            {{ rf.author(class_="form-control", placeholder="author") }}
                        </div>
                        <div class="form-group">
                            {{ rf.comment.label }}
                            {{ rf.comment(class_="form-control", placeholder="comment reply") }}
                        </div><button type="submit" class="btn btn-default">Add Reply</button>
                    </form>
                    </div>
                </li>
        </ul>

    </div>
    {% endfor %}

    <form role="form" method="post" action="{{ url_for('.save_comment', catid=cat.id) }}">
        {{  form.hidden_tag() }}
        <div class="panel panel-primary">
            <div class="panel-heading">Add a comment</div>
            <div class="panel-body">
                <div class="form-group">
                    {{ form.author.label }}
                    {{ form.author(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.comment.label }}
                    {{ form.comment(class_="form-control") }}
                </div><div class="panel-footer"><button type="submit" class="btn btn-primary">Add Comment</button></div>
            </div>
        </div>
    </form>

{% endblock %}

templates/list.html
{%  extends "base.html" %}

{%  block page_header %}
    <h2>All Lolcats</h2>
{% endblock %}

{%  block content %}

    <div class="container">
        <div class="well well-sm">There are {{ total }} lolcats for you</div>

        <div class="row">
        {%  for cat in cats %}
            <div class="col-sm-6 col-md-3 thumbnail">
            <a href="{{ url_for('.one', catid=cat.id) }}">
                <img src="{{ url_for('.image_data', catid=cat.id) }}" alt="{{ cat.title }}" />
                <h3>{{ cat.title }}</h3>
            </a>
            <p>{{ cat.blurb }}</p>
            <p>{{  cat.comments | length }} comments</p>
            <p>
                <div class="btn-group" role="group">
                    <a href="{{ url_for('.one', catid=cat.id) }}" class="btn btn-primary">view</a>
                    <div class="btn-group" role="group">
                        <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" role="button">options<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url_for('.edit', catid = cat.id) }}"><span class="glyphicon glyphicon-edit" aria-label="true"></span> edit</a></li>
                            <li><a href="{{ url_for('.delete', catid = cat.id) }}"><span class="glyphicon glyphicon-erase" aria-label="true"></span> delete</a></li>
                        </ul>
                    </div>
                </div>
            </p>
        </div>
        {%  endfor  %}
        </div>
    </div>



    <ul class="pagination">
    {%  if page > 0 %}
    <li>
          <a href="{{ url_for( '.home', page=page - 1) }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
    </li>
    {%  endif %}

    {% for i in range(0, pages) %}
        <li class="{{ "active" if page == loop.index0 }}"><a href="{{ url_for('.home', page=loop.index0) }}">{{ loop.index }}</a></li>
    {% endfor %}

    {%  if (page + 1) < pages %}
    <li>
          <a href="{{ url_for('.home', page=page + 1) }}" aria-label="Previous">
            <span aria-hidden="true">&raquo;</span>
          </a>
    {%  endif %}
    </ul>

{% endblock %}